### ISSUE TITLE
Problem with permission 

### ISSUE THREAD

**Issue by PetmePant** [mriverodorta/devtips-cli#4]
Hello, I dont know if that still works but I try to run the commands after I install it on my macbook but I get this error. -bash: devtips: command not found

**Comment by mriverodorta** [comment]
maybe you need to add sudo for it to copy to /usr/local/bin/devtips

**Comment by PetmePant** [comment]
yep that worked well. Btw, you know any way that I could upgrade the file directory to the new version of jekyll or it works also fine like that (updating post and etc) ? and if yes how I could without affecting the way that this build works with gulp and etc

**Comment by mriverodorta** [comment]
you can use a normal jekyll directory structure, every time you change a file gulp will trigger a jekyll build so jekyll will compile your posts too
